### ISSUE TITLE
sbomls breaks when passing spdx.json SBOM

### ISSUE THREAD

**Issue by sdd4181** [elear/sbomtools#1]
I tried `sbomls -f spdx.json` for two different SPDX SBOMs ([Example 10](https://github.com/spdx/spdx-examples/blob/master/example10/spdx/hello-source.spdx.json), [Example 7](https://github.com/spdx/spdx-examples/blob/master/example7/spdx/example7-golang.spdx.json)). In both cases, I get a KeyError but for different issues. For Example 10, I get the following: 
![image](https://user-images.githubusercontent.com/69910407/231254311-ea2faa27-6779-4162-983c-d21bcdb0935b.png)

For example 7, I get this: 
![image](https://user-images.githubusercontent.com/69910407/231254420-d6dfdd49-6aee-47de-ac8c-6a1b0500c4a4.png)

Please let me know if you need any other information!

**Comment by sdd4181** [comment]
The same error occurs (in a different spot) when using sbomupdate:
![image](https://user-images.githubusercontent.com/69910407/231258020-851f628c-2b4b-4957-a10b-4a1a40921d3d.png)

and sbomrm:
![image](https://user-images.githubusercontent.com/69910407/231258209-2902a5dd-8873-420a-b66b-eb7116551c57.png)

**Comment by riteshnoronha** [comment]
You can try https://github.com/interlynk-io/sbomgr

**Comment by elear** [comment]
Thanks for the report.   Will try to have a fix in the next few days.

**Comment by elear** [comment]
The problem is that version has an cardinality of 0..1 and this tool assumes cardinality of 1.

**Comment by elear** [comment]
@riteshnoronha thanks again for your report.  In the one case, Example 10, there is indeed a bug in the code, and .  However, Example 7 is not well formed SPDX because PackageName is not defined in the [schema](https://github.com/spdx/spdx-spec/blob/master/schemas/spdx-schema.json). That should simply be "name".  That is one of many errors with that example.  I have opened Issue 62 with the SPDX project to point this out.  Again, thanks for the report.  A fix will be delivered to Pypi over the next few days.
